name: Publish NuGet Package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build -c Release

    - name: Pack
      run: dotnet pack -c Release

    - name: Publish NuGet package
      uses: nuget/nuget-publish@v1
      with:
        nuget_version: '5.x'
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
