name: Publish NuGet Package

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: false
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Build
      run: dotnet build -c Release

    - name: Pack
      run: dotnet pack -c Release

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v2.0.0
      with:
        nuget-version: latest
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./**/*.nupkg --skip-duplicate --no-symbols true
